package com.salescrm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdAllPropertiesEquals(Ad expected, Ad actual) {
        assertAdAutoGeneratedPropertiesEquals(expected, actual);
        assertAdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdAllUpdatablePropertiesEquals(Ad expected, Ad actual) {
        assertAdUpdatableFieldsEquals(expected, actual);
        assertAdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdAutoGeneratedPropertiesEquals(Ad expected, Ad actual) {
        assertThat(actual)
            .as("Verify Ad auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdUpdatableFieldsEquals(Ad expected, Ad actual) {
        assertThat(actual)
            .as("Verify Ad relevant properties")
            .satisfies(a -> assertThat(a.getExternalId()).as("check externalId").isEqualTo(expected.getExternalId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdUpdatableRelationshipsEquals(Ad expected, Ad actual) {
        assertThat(actual)
            .as("Verify Ad relationships")
            .satisfies(a -> assertThat(a.getAdSet()).as("check adSet").isEqualTo(expected.getAdSet()));
    }
}
