package com.salescrm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdSetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdSetAllPropertiesEquals(AdSet expected, AdSet actual) {
        assertAdSetAutoGeneratedPropertiesEquals(expected, actual);
        assertAdSetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdSetAllUpdatablePropertiesEquals(AdSet expected, AdSet actual) {
        assertAdSetUpdatableFieldsEquals(expected, actual);
        assertAdSetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdSetAutoGeneratedPropertiesEquals(AdSet expected, AdSet actual) {
        assertThat(actual)
            .as("Verify AdSet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdSetUpdatableFieldsEquals(AdSet expected, AdSet actual) {
        assertThat(actual)
            .as("Verify AdSet relevant properties")
            .satisfies(a -> assertThat(a.getExternalId()).as("check externalId").isEqualTo(expected.getExternalId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdSetUpdatableRelationshipsEquals(AdSet expected, AdSet actual) {
        assertThat(actual)
            .as("Verify AdSet relationships")
            .satisfies(a -> assertThat(a.getCampaign()).as("check campaign").isEqualTo(expected.getCampaign()));
    }
}
