package com.salescrm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LeadFormAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadFormAllPropertiesEquals(LeadForm expected, LeadForm actual) {
        assertLeadFormAutoGeneratedPropertiesEquals(expected, actual);
        assertLeadFormAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadFormAllUpdatablePropertiesEquals(LeadForm expected, LeadForm actual) {
        assertLeadFormUpdatableFieldsEquals(expected, actual);
        assertLeadFormUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadFormAutoGeneratedPropertiesEquals(LeadForm expected, LeadForm actual) {
        assertThat(actual)
            .as("Verify LeadForm auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadFormUpdatableFieldsEquals(LeadForm expected, LeadForm actual) {
        assertThat(actual)
            .as("Verify LeadForm relevant properties")
            .satisfies(a -> assertThat(a.getExternalId()).as("check externalId").isEqualTo(expected.getExternalId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadFormUpdatableRelationshipsEquals(LeadForm expected, LeadForm actual) {
        // empty method
    }
}
