package com.salescrm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LeadPreferenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadPreferenceAllPropertiesEquals(LeadPreference expected, LeadPreference actual) {
        assertLeadPreferenceAutoGeneratedPropertiesEquals(expected, actual);
        assertLeadPreferenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadPreferenceAllUpdatablePropertiesEquals(LeadPreference expected, LeadPreference actual) {
        assertLeadPreferenceUpdatableFieldsEquals(expected, actual);
        assertLeadPreferenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadPreferenceAutoGeneratedPropertiesEquals(LeadPreference expected, LeadPreference actual) {
        assertThat(actual)
            .as("Verify LeadPreference auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadPreferenceUpdatableFieldsEquals(LeadPreference expected, LeadPreference actual) {
        assertThat(actual)
            .as("Verify LeadPreference relevant properties")
            .satisfies(a -> assertThat(a.getMattressType()).as("check mattressType").isEqualTo(expected.getMattressType()))
            .satisfies(a -> assertThat(a.getMattressSize()).as("check mattressSize").isEqualTo(expected.getMattressSize()))
            .satisfies(a -> assertThat(a.getBudgetRange()).as("check budgetRange").isEqualTo(expected.getBudgetRange()))
            .satisfies(a -> assertThat(a.getPurchaseTimeline()).as("check purchaseTimeline").isEqualTo(expected.getPurchaseTimeline()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadPreferenceUpdatableRelationshipsEquals(LeadPreference expected, LeadPreference actual) {
        assertThat(actual)
            .as("Verify LeadPreference relationships")
            .satisfies(a -> assertThat(a.getLead()).as("check lead").isEqualTo(expected.getLead()));
    }
}
