# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  r2dbc:
    username: salesCRM
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2I4OWUxZGM0YTk2MzQ0ODc4YzNiMjA4NWY1MmFiMDZmYzI5ZjQ0MWZhNTQ2ZTQ2MGQ1ZjcyYjc3ZjFkYjYxYmU1NDE1Njg4YTE1NGZiN2Y4N2M0YTdkZTliMTZkYjNkYjMwNWJhNDUyZDhmYTg5YjY3MDIwYWNmZDQ1MDE2Yjg=
